Create table HARI_USER_TABLE(
USERID INT,USERNAME VARCHAR(40),USERPASS INT)


Create table HARI_STOCK_CALC(
STOCKID INT,STOCK_NAME VARCHAR(40) ,AVAILABE_STOCKS INT)

DROP TABLE HARI_STOCK_CALC


alter  procedure HARI_ADD_DATA 
 @USERID INT , @USERNAME VARCHAR(40),@USERPASS INT
as
begin
insert into HARI_USER_TABLE (USERID,USERNAME,USERPASS) values (@USERID,@USERNAME,@USERPASS)
end
exec HARI_ADD_DATA '7','198','183'

SELECT * FROM HARI_USER_TABLE
select * from HARI_STOCK_CALC


ALTER  procedure HARI_ADD_CALC 
@STOCKID INT,@STOCK_NAME VARCHAR(40),@AVAILABE_STOCKS INT
as
begin
insert into HARI_STOCK_CALC (STOCKID,STOCK_NAME,AVAILABE_STOCKS) 
values (@STOCKID,@STOCK_NAME,@AVAILABE_STOCKS)
end
exec HARI_ADD_CALC '3','Platinum','600'

create  table HARI_FINAL_TABLE(USERNAME VARCHAR(40),STOCK_NAME VARCHAR(40),NO_OF_SHARES_PURCHASE INT)

ALTER procedure HARI_FINAL_CALC 
@USERNAME VARCHAR(40),@STOCK_NAME VARCHAR(40),@NO_OF_SHARES_PURCHASE INT,@USERPASS INT
as
begin
DECLARE @AVBLE INT
DECLARE @USER  VARCHAR(40)
DECLARE @PASS INT
SET @PASS=(SELECT USERPASS FROM HARI_USER_TABLE WHERE USERPASS=@USERPASS)
SET @USER=(SELECT USERNAME FROM HARI_USER_TABLE WHERE USERNAME=@USERNAME)
SET @AVBLE=(SELECT AVAILABE_STOCKS FROM HARI_STOCK_CALC WHERE STOCK_NAME=@STOCK_NAME)
--print @USER
--Print @AVBLE
--end
IF(@NO_OF_SHARES_PURCHASE<=@AVBLE)
begin
IF(@USERNAME=@USER)
BEGIN
IF(@USERPASS=@PASS)
BEGIN
insert into HARI_FINAL_TABLE (USERNAME,STOCK_NAME,NO_OF_SHARES_PURCHASE) 
values (@USERNAME,@STOCK_NAME,@NO_OF_SHARES_PURCHASE)
END
ELSE
BEGIN
PRINT 'INVALID PASSWORD'
END
END
ELSE
BEGIN
PRINT 'INVALID USER NAME'
END
end
ELSE
BEGIN
PRINT 'STOCK IS LOW'
END
end
EXEC HARI_FINAL_CALC 'HARI','Gold','200','123'

select *from HARI_FINAL_TABLE
select *from  HARI_USER_TABLE
SELECT * FROM HARI_STOCK_CALC
   








 
 







       

		 
