CREATE TABLE HARI_USER_TABLE(
USERID INT,USERNAME VARCHAR(40),USERPASS INT)


CREATE TABLE HARI_STOCK_CALC(
STOCKID INT,STOCK_NAME VARCHAR(40) ,AVAILABE_STOCKS INT)

DROP TABLE HARI_STOCK_CALC


ALTER  PROCEDURE HARI_ADD_DATA 
 @USERID INT , @USERNAME VARCHAR(40),@USERPASS INT
AS
BEGIN
INSERT INTO HARI_USER_TABLE (USERID,USERNAME,USERPASS) VALUES (@USERID,@USERNAME,@USERPASS)
END
EXEC HARI_ADD_DATA '7','198','183'

SELECT * FROM HARI_USER_TABLE
SELECT * FROM HARI_STOCK_CALC


ALTER  PROCEDURE HARI_ADD_CALC 
@STOCKID INT,@STOCK_NAME VARCHAR(40),@AVAILABE_STOCKS INT
AS
BEGIN
INSERT INTO HARI_STOCK_CALC (STOCKID,STOCK_NAME,AVAILABE_STOCKS) 
VALUES (@STOCKID,@STOCK_NAME,@AVAILABE_STOCKS)
END
EXEC HARI_ADD_CALC '3','Platinum','600'

CREATE  TABLE HARI_FINAL_TABLE(USERNAME VARCHAR(40),STOCK_NAME VARCHAR(40),NO_OF_SHARES_PURCHASE INT)

ALTER procedure HARI_FINAL_CALC 
@USERNAME VARCHAR(40),@STOCK_NAME VARCHAR(40),@NO_OF_SHARES_PURCHASE INT,@USERPASS INT
AS
BEGIN
DECLARE @AVBLE INT
DECLARE @USER  VARCHAR(40)
DECLARE @PASS INT
SET @PASS=(SELECT USERPASS FROM HARI_USER_TABLE WHERE USERPASS=@USERPASS)
SET @USER=(SELECT USERNAME FROM HARI_USER_TABLE WHERE USERNAME=@USERNAME)
SET @AVBLE=(SELECT AVAILABE_STOCKS FROM HARI_STOCK_CALC WHERE STOCK_NAME=@STOCK_NAME)
--print @USER
--Print @AVBLE
--end
IF(@NO_OF_SHARES_PURCHASE<=@AVBLE)
BEGIN
IF(@USERNAME=@USER)
BEGIN
IF(@USERPASS=@PASS)
BEGIN
INSERT INTO HARI_FINAL_TABLE (USERNAME,STOCK_NAME,NO_OF_SHARES_PURCHASE) 
VALUES (@USERNAME,@STOCK_NAME,@NO_OF_SHARES_PURCHASE)
END
ELSE
BEGIN
PRINT 'INVALID PASSWORD'
END
END
ELSE
BEGIN
PRINT 'INVALID USER NAME'
END
END
ELSE
BEGIN
PRINT 'STOCK IS LOW'
END
END
EXEC HARI_FINAL_CALC 'HARI','Gold','200','123'

SELECT *FROM HARI_FINAL_TABLE
select *FROM  HARI_USER_TABLE
SELECT * FROM HARI_STOCK_CALC
   








 
 







       

		 
